### ISSUE TITLE
Could LiveLogViewer use stdin?

### ISSUE THREAD

**Issue by canadaduane** [EnakNalla/LiveLogViewer#2]
I'm curious if LiveLogViewer could take as its log source data streaming to stdin?

For example:

```
turbo dev | LiveLogViewer
```

(turborepo is a popular build and dev tool for javascript monorepos--in the example above, imagine a dozen or so services all spewing log output to stdout)

**Comment by Kane-Allan** [comment]
This is interesting. 
I just implemented it, but it is rough around the edges and will need more work.

If you want to test it out I have put up the build here
https://github.com/EnakNalla/LiveLogViewer/releases/tag/v1.4.0

**Comment by Kane-Allan** [comment]
Going to consider this complete with the new 1.4.0 release I just created which includes other new features, unless you tell me otherwise.

https://github.com/EnakNalla/LiveLogViewer/releases/tag/v1.4.0

**Comment by canadaduane** [comment]
Looks good here, thanks!
