### ISSUE TITLE
Build for Linux?

### ISSUE THREAD

**Issue by canadaduane** [EnakNalla/LiveLogViewer#3]
If it's an easy thing--perhaps a build for Linux could be added?

```
$ ~/Downloads/LiveLogViewer-amd64-portable.exe 
bash: /home/duane/Downloads/LiveLogViewer-amd64-portable.exe: cannot execute binary file: Exec format error
```

I thought for a moment that "portable" meant https://justine.lol/ape.html :D

**Comment by Kane-Allan** [comment]
Assuming amd64,
https://github.com/EnakNalla/LiveLogViewer/releases/download/v1.4.0/LiveLogViewer-linux-amd64

I have no way of testing the build so 🤞 it works.

**Comment by canadaduane** [comment]
It works!!

![image](https://user-images.githubusercontent.com/129/233806108-ba07cce5-70a0-48d5-b1a4-1f732d3f0d1d.png)
 
 Thanks :)
